# https://developers.home-assistant.io/docs/apps/configuration#app-configuration
name: YT Search & Download
version: 1.0.12
slug: yt-search-download
description: A Home Assistant app for searching and downloading Youtube videos
arch:
  - amd64
  - aarch64
url: https://github.com/punxaphil/yt-search-download
ingress: true
ingress_port: 3000
map:
  - type: share
    read_only: False
  - type: media
    read_only: False
options:
  saveDir: /media/yt-search-download
  stateDir: /data
  cookiesFile: /share/cookie.txt
schema:
  saveDir: "str"
  stateDir: "str"
  cookiesFile: "str"
image: ghcr.io/punxaphil/yt-search-download
init: false
