name: Build image and publish

on:
  push:
    branches:
      - main

env:
  ARCHITECTURES: '["amd64", "aarch64"]'
  IMAGE_NAME: yt-search-download

permissions:
  contents: read

jobs:
  # check version in config.yaml, if no docker image has been published with that version,
  # proceed with build and push using version in config.yaml
  check-version:
    name: Check version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.check-version.outputs.version }}
    steps:
      - uses: actions/checkout@v6

      - name: Check version in config.yaml
        id: check-version
        run: |
          VERSION=$(yq e '.version' yt-search-download/config.yaml)
          echo "Version in config.yaml: $VERSION"

          # Check if the image with the specified version exists in GitHub Container Registry
          IMAGE_EXISTS=$(gh api -H "Accept: application/vnd.github.v3+json" /user/packages/container/$IMAGE_NAME/versions | jq -r --arg VERSION "$VERSION" '.[] | select(.metadata.container.tags[] == $VERSION) | .id')

          if [ -z "$IMAGE_EXISTS" ]; then
            echo "Image with version $VERSION does not exist. Proceeding with build and push."
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "Image with version $VERSION already exists. Skipping build and push."
          fi
  init:
    if: ${{ needs.check-version.outputs.version != '' }}
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6

      - name: Get build matrix
        id: matrix
        uses: home-assistant/builder/actions/prepare-multi-arch-matrix@2026.06.0
        with:
          architectures: ${{ env.ARCHITECTURES }}
          image-name: ${{ env.IMAGE_NAME }}

  build:
    if: ${{ needs.check-version.outputs.version != '' }}
    name: Build ${{ matrix.arch }} image
    needs: init
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read # To check out the code
      id-token: write # Write needed for Cosign signing (issue OIDC token for signing)
      packages: write # To push built images to GitHub Container Registry
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.init.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v6

      - name: Build image
        uses: home-assistant/builder/actions/build-image@2026.06.0
        with:
          arch: ${{ matrix.arch }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ matrix.image }}
          image-tags: |
            ${{ needs.check-version.outputs.version }}
            latest
          push: 'true'
          version: ${{ needs.check-version.outputs.version }}
          context: ./yt-search-download


  manifest:
    if: ${{ needs.check-version.outputs.version != '' }}
    name: Publish multi-arch manifest
    needs: [init, build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Write needed for Cosign signing (issue OIDC token for signing)
      packages: write # To push the manifest to GitHub Container Registry
    steps:
      - name: Publish multi-arch manifest
        uses: home-assistant/builder/actions/publish-multi-arch-manifest@2026.06.0
        with:
          architectures: ${{ env.ARCHITECTURES }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          image-name: ${{ env.IMAGE_NAME }}
          image-tags: |
            ${{ needs.check-version.outputs.version }}
            latest
